##########################
## SERVER CONFIGURATION ##
##########################
server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ON_PARAM
    include-exception: true
url: https:localhost:${server.port}

############################
## DATABASE CONFIGURATION ##
############################
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
  h2.console.enabled: true

######################################
## OPEN API - SWAGGER CONFIGURATION ##
######################################
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

#############
## LOGGING ##
#############
# Logging config for SQL queries
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.generate_statistics: true


logging:
  level:
    org.hibernate:
      engine.jdbc.batch.internal.BatchingBatch: DEBUG
